### ISSUE TITLE
Error if missing certain frontmatter

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/web-engineering-issues#16]
If the website doesn't have at least one page with this frontmatter (or similar, values don't matter) then the site will fail to build:

```yml
---
duration: ''
experimental: false
staticLink: false
---
```

More context in [this slack thread](https://prisma-company.slack.com/archives/C012S4U28PM/p1600355198000300).

The solution is to create a dummy page with this frontmatter for now:

```yml
experimental: false,
duration: '',
staticLink: false,
hidePage: true
```
